#!/usr/bin/env bash
#
# unbootstrap uninstalls things.

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd)

uninstall_dotfiles () {
  info 'uninstalling dotfiles'

  for src in $(find "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink')
  do
    dst="$HOME/.$(basename "${src%.*}")"
    echo "Removing $dst"
    rm "$dst"
  done
}
